apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana

