apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 32001
  selector:
    app: prometheus

